### ISSUE TITLE
Import ModuleNotFoundError

### ISSUE THREAD

**Issue by James-G-Hill** [antiprism/antiprism_python#1]
'import antiprism', 'import antiprism_python' and importing 'antiprism-python' via importlib.import_module all result in 'ModuleNotFoundError'.

How to import this library?  Can instructions or an example be added?  For example, I would like to import 'geodesic.py', how would I do that?

**Comment by antiprism** [comment]
Hi James

The project is a set of programs, rather than a library package, but if you wish to import the code you could do this
```
adrian@adrian-laptop:~/data/proj/tmp/antpy$ python3
Python 3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import anti_lib_progs.geodesic
>>> verts = []
>>> edges = {}
>>> faces = []
>>> anti_lib_progs.geodesic.get_poly('t', verts, edges, faces)
1
>>> verts
[Vec(-0.5773502691896258, 0.5773502691896258, -0.5773502691896258), Vec(-0.5773502691896258, -0.5773502691896258, 0.5773502691896258), Vec(0.5773502691896258, 0.5773502691896258, 0.5773502691896258), Vec(0.5773502691896258, -0.5773502691896258, -0.5773502691896258)]
```

If you just want to import the common library

`import anti_lib`

Adrian.

**Comment by James-G-Hill** [comment]
Thanks, yes, I realised why this was unlikely to work after a short sleep; it was a late night.  This is definitely useful though.  Thanks!
